# Default values for helm.
image:
  repository: github.com/pmoth/ntms
  tag: 0.1.1
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
httpPort: 8080
replicas: 3
storage: 0.5Gi
storageClassName: local-storage
service:
  lb: true
